export const countries = [
  { code: 'AD', name: 'Andorra', flag: 'https://flagcdn.com/w40/ad.png', dialCode: '+376' },
  { code: 'AE', name: 'United Arab Emirates', flag: 'https://flagcdn.com/w40/ae.png', dialCode: '+971' },
  { code: 'AF', name: 'Afghanistan', flag: 'https://flagcdn.com/w40/af.png', dialCode: '+93' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: 'https://flagcdn.com/w40/ag.png', dialCode: '+1268' },
  { code: 'AI', name: 'Anguilla', flag: 'https://flagcdn.com/w40/ai.png', dialCode: '+1264' },
  { code: 'AL', name: 'Albania', flag: 'https://flagcdn.com/w40/al.png', dialCode: '+355' },
  { code: 'AM', name: 'Armenia', flag: 'https://flagcdn.com/w40/am.png', dialCode: '+374' },
  { code: 'AO', name: 'Angola', flag: 'https://flagcdn.com/w40/ao.png', dialCode: '+244' },
  { code: 'AQ', name: 'Antarctica', flag: 'https://flagcdn.com/w40/aq.png', dialCode: '+672' },
  { code: 'AR', name: 'Argentina', flag: 'https://flagcdn.com/w40/ar.png', dialCode: '+54' },
  { code: 'AS', name: 'American Samoa', flag: 'https://flagcdn.com/w40/as.png', dialCode: '+1684' },
  { code: 'AT', name: 'Austria', flag: 'https://flagcdn.com/w40/at.png', dialCode: '+43' },
  { code: 'AU', name: 'Australia', flag: 'https://flagcdn.com/w40/au.png', dialCode: '+61' },
  { code: 'AW', name: 'Aruba', flag: 'https://flagcdn.com/w40/aw.png', dialCode: '+297' },
  { code: 'AX', name: 'Åland Islands', flag: 'https://flagcdn.com/w40/ax.png', dialCode: '+358' },
  { code: 'AZ', name: 'Azerbaijan', flag: 'https://flagcdn.com/w40/az.png', dialCode: '+994' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/w40/ba.png', dialCode: '+387' },
  { code: 'BB', name: 'Barbados', flag: 'https://flagcdn.com/w40/bb.png', dialCode: '+1246' },
  { code: 'BD', name: 'Bangladesh', flag: 'https://flagcdn.com/w40/bd.png', dialCode: '+880' },
  { code: 'BE', name: 'Belgium', flag: 'https://flagcdn.com/w40/be.png', dialCode: '+32' },
  { code: 'BF', name: 'Burkina Faso', flag: 'https://flagcdn.com/w40/bf.png', dialCode: '+226' },
  { code: 'BG', name: 'Bulgaria', flag: 'https://flagcdn.com/w40/bg.png', dialCode: '+359' },
  { code: 'BH', name: 'Bahrain', flag: 'https://flagcdn.com/w40/bh.png', dialCode: '+973' },
  { code: 'BI', name: 'Burundi', flag: 'https://flagcdn.com/w40/bi.png', dialCode: '+257' },
  { code: 'BJ', name: 'Benin', flag: 'https://flagcdn.com/w40/bj.png', dialCode: '+229' },
  { code: 'BL', name: 'Saint Barthélemy', flag: 'https://flagcdn.com/w40/bl.png', dialCode: '+590' },
  { code: 'BM', name: 'Bermuda', flag: 'https://flagcdn.com/w40/bm.png', dialCode: '+1441' },
  { code: 'BN', name: 'Brunei Darussalam', flag: 'https://flagcdn.com/w40/bn.png', dialCode: '+673' },
  { code: 'BO', name: 'Bolivia', flag: 'https://flagcdn.com/w40/bo.png', dialCode: '+591' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flag: 'https://flagcdn.com/w40/bq.png', dialCode: '+599' },
  { code: 'BR', name: 'Brazil', flag: 'https://flagcdn.com/w40/br.png', dialCode: '+55' },
  { code: 'BS', name: 'Bahamas', flag: 'https://flagcdn.com/w40/bs.png', dialCode: '+1242' },
  { code: 'BT', name: 'Bhutan', flag: 'https://flagcdn.com/w40/bt.png', dialCode: '+975' },
  { code: 'BV', name: 'Bouvet Island', flag: 'https://flagcdn.com/w40/bv.png', dialCode: '+47' },
  { code: 'BW', name: 'Botswana', flag: 'https://flagcdn.com/w40/bw.png', dialCode: '+267' },
  { code: 'BY', name: 'Belarus', flag: 'https://flagcdn.com/w40/by.png', dialCode: '+375' },
  { code: 'BZ', name: 'Belize', flag: 'https://flagcdn.com/w40/bz.png', dialCode: '+501' },
  { code: 'CA', name: 'Canada', flag: 'https://flagcdn.com/w40/ca.png', dialCode: '+1' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', flag: 'https://flagcdn.com/w40/cc.png', dialCode: '+61' },
  { code: 'CD', name: 'Democratic Republic of Congo', flag: 'https://flagcdn.com/w40/cd.png', dialCode: '+243' },
  { code: 'CF', name: 'Central African Republic', flag: 'https://flagcdn.com/w40/cf.png', dialCode: '+236' },
  { code: 'CG', name: 'Congo', flag: 'https://flagcdn.com/w40/cg.png', dialCode: '+242' },
  { code: 'CH', name: 'Switzerland', flag: 'https://flagcdn.com/w40/ch.png', dialCode: '+41' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: 'https://flagcdn.com/w40/ci.png', dialCode: '+225' },
  { code: 'CK', name: 'Cook Islands', flag: 'https://flagcdn.com/w40/ck.png', dialCode: '+682' },
  { code: 'CL', name: 'Chile', flag: 'https://flagcdn.com/w40/cl.png', dialCode: '+56' },
  { code: 'CM', name: 'Cameroon', flag: 'https://flagcdn.com/w40/cm.png', dialCode: '+237' },
  { code: 'CN', name: 'China', flag: 'https://flagcdn.com/w40/cn.png', dialCode: '+86' },
  { code: 'CO', name: 'Colombia', flag: 'https://flagcdn.com/w40/co.png', dialCode: '+57' },
  { code: 'CR', name: 'Costa Rica', flag: 'https://flagcdn.com/w40/cr.png', dialCode: '+506' },
  { code: 'CU', name: 'Cuba', flag: 'https://flagcdn.com/w40/cu.png', dialCode: '+53' },
  { code: 'CV', name: 'Cape Verde', flag: 'https://flagcdn.com/w40/cv.png', dialCode: '+238' },
  { code: 'CW', name: 'Curaçao', flag: 'https://flagcdn.com/w40/cw.png', dialCode: '+599' },
  { code: 'CX', name: 'Christmas Island', flag: 'https://flagcdn.com/w40/cx.png', dialCode: '+61' },
  { code: 'CY', name: 'Cyprus', flag: 'https://flagcdn.com/w40/cy.png', dialCode: '+357' },
  { code: 'CZ', name: 'Czech Republic', flag: 'https://flagcdn.com/w40/cz.png', dialCode: '+420' },
  { code: 'DE', name: 'Germany', flag: 'https://flagcdn.com/w40/de.png', dialCode: '+49' },
  { code: 'DJ', name: 'Djibouti', flag: 'https://flagcdn.com/w40/dj.png', dialCode: '+253' },
  { code: 'DK', name: 'Denmark', flag: 'https://flagcdn.com/w40/dk.png', dialCode: '+45' },
  { code: 'DM', name: 'Dominica', flag: 'https://flagcdn.com/w40/dm.png', dialCode: '+1767' },
  { code: 'DO', name: 'Dominican Republic', flag: 'https://flagcdn.com/w40/do.png', dialCode: '+1' },
  { code: 'DZ', name: 'Algeria', flag: 'https://flagcdn.com/w40/dz.png', dialCode: '+213' },
  { code: 'EC', name: 'Ecuador', flag: 'https://flagcdn.com/w40/ec.png', dialCode: '+593' },
  { code: 'EE', name: 'Estonia', flag: 'https://flagcdn.com/w40/ee.png', dialCode: '+372' },
  { code: 'EG', name: 'Egypt', flag: 'https://flagcdn.com/w40/eg.png', dialCode: '+20' },
  { code: 'EH', name: 'Western Sahara', flag: 'https://flagcdn.com/w40/eh.png', dialCode: '+212' },
  { code: 'ER', name: 'Eritrea', flag: 'https://flagcdn.com/w40/er.png', dialCode: '+291' },
  { code: 'ES', name: 'Spain', flag: 'https://flagcdn.com/w40/es.png', dialCode: '+34' },
  { code: 'ET', name: 'Ethiopia', flag: 'https://flagcdn.com/w40/et.png', dialCode: '+251' },
  { code: 'FI', name: 'Finland', flag: 'https://flagcdn.com/w40/fi.png', dialCode: '+358' },
  { code: 'FJ', name: 'Fiji', flag: 'https://flagcdn.com/w40/fj.png', dialCode: '+679' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', flag: 'https://flagcdn.com/w40/fk.png', dialCode: '+500' },
  { code: 'FM', name: 'Micronesia', flag: 'https://flagcdn.com/w40/fm.png', dialCode: '+691' },
  { code: 'FO', name: 'Faroe Islands', flag: 'https://flagcdn.com/w40/fo.png', dialCode: '+298' },
  { code: 'FR', name: 'France', flag: 'https://flagcdn.com/w40/fr.png', dialCode: '+33' },
  { code: 'GA', name: 'Gabon', flag: 'https://flagcdn.com/w40/ga.png', dialCode: '+241' },
  { code: 'GB', name: 'United Kingdom', flag: 'https://flagcdn.com/w40/gb.png', dialCode: '+44' },
  { code: 'GD', name: 'Grenada', flag: 'https://flagcdn.com/w40/gd.png', dialCode: '+1473' },
  { code: 'GE', name: 'Georgia', flag: 'https://flagcdn.com/w40/ge.png', dialCode: '+995' },
  { code: 'GF', name: 'French Guiana', flag: 'https://flagcdn.com/w40/gf.png', dialCode: '+594' },
  { code: 'GG', name: 'Guernsey', flag: 'https://flagcdn.com/w40/gg.png', dialCode: '+44' },
  { code: 'GH', name: 'Ghana', flag: 'https://flagcdn.com/w40/gh.png', dialCode: '+233' },
  { code: 'GI', name: 'Gibraltar', flag: 'https://flagcdn.com/w40/gi.png', dialCode: '+350' },
  { code: 'GL', name: 'Greenland', flag: 'https://flagcdn.com/w40/gl.png', dialCode: '+299' },
  { code: 'GM', name: 'Gambia', flag: 'https://flagcdn.com/w40/gm.png', dialCode: '+220' },
  { code: 'GN', name: 'Guinea', flag: 'https://flagcdn.com/w40/gn.png', dialCode: '+224' },
  { code: 'GP', name: 'Guadeloupe', flag: 'https://flagcdn.com/w40/gp.png', dialCode: '+590' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: 'https://flagcdn.com/w40/gq.png', dialCode: '+240' },
  { code: 'GR', name: 'Greece', flag: 'https://flagcdn.com/w40/gr.png', dialCode: '+30' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', flag: 'https://flagcdn.com/w40/gs.png', dialCode: '+500' },
  { code: 'GT', name: 'Guatemala', flag: 'https://flagcdn.com/w40/gt.png', dialCode: '+502' },
  { code: 'GU', name: 'Guam', flag: 'https://flagcdn.com/w40/gu.png', dialCode: '+1671' },
  { code: 'GW', name: 'Guinea-Bissau', flag: 'https://flagcdn.com/w40/gw.png', dialCode: '+245' },
  { code: 'GY', name: 'Guyana', flag: 'https://flagcdn.com/w40/gy.png', dialCode: '+592' },
  { code: 'HK', name: 'Hong Kong', flag: 'https://flagcdn.com/w40/hk.png', dialCode: '+852' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', flag: 'https://flagcdn.com/w40/hm.png', dialCode: '+672' },
  { code: 'HN', name: 'Honduras', flag: 'https://flagcdn.com/w40/hn.png', dialCode: '+504' },
  { code: 'HR', name: 'Croatia', flag: 'https://flagcdn.com/w40/hr.png', dialCode: '+385' },
  { code: 'HT', name: 'Haiti', flag: 'https://flagcdn.com/w40/ht.png', dialCode: '+509' },
  { code: 'HU', name: 'Hungary', flag: 'https://flagcdn.com/w40/hu.png', dialCode: '+36' },
  { code: 'ID', name: 'Indonesia', flag: 'https://flagcdn.com/w40/id.png', dialCode: '+62' },
  { code: 'IE', name: 'Ireland', flag: 'https://flagcdn.com/w40/ie.png', dialCode: '+353' },
  { code: 'IL', name: 'Israel', flag: 'https://flagcdn.com/w40/il.png', dialCode: '+972' },
  { code: 'IM', name: 'Isle of Man', flag: 'https://flagcdn.com/w40/im.png', dialCode: '+44' },
  { code: 'IN', name: 'India', flag: 'https://flagcdn.com/w40/in.png', dialCode: '+91' },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: 'https://flagcdn.com/w40/io.png', dialCode: '+246' },
  { code: 'IQ', name: 'Iraq', flag: 'https://flagcdn.com/w40/iq.png', dialCode: '+964' },
  { code: 'IR', name: 'Iran', flag: 'https://flagcdn.com/w40/ir.png', dialCode: '+98' },
  { code: 'IS', name: 'Iceland', flag: 'https://flagcdn.com/w40/is.png', dialCode: '+354' },
  { code: 'IT', name: 'Italy', flag: 'https://flagcdn.com/w40/it.png', dialCode: '+39' },
  { code: 'JE', name: 'Jersey', flag: 'https://flagcdn.com/w40/je.png', dialCode: '+44' },
  { code: 'JM', name: 'Jamaica', flag: 'https://flagcdn.com/w40/jm.png', dialCode: '+1876' },
  { code: 'JO', name: 'Jordan', flag: 'https://flagcdn.com/w40/jo.png', dialCode: '+962' },
  { code: 'JP', name: 'Japan', flag: 'https://flagcdn.com/w40/jp.png', dialCode: '+81' },
  { code: 'KE', name: 'Kenya', flag: 'https://flagcdn.com/w40/ke.png', dialCode: '+254' },
  { code: 'KG', name: 'Kyrgyzstan', flag: 'https://flagcdn.com/w40/kg.png', dialCode: '+996' },
  { code: 'KH', name: 'Cambodia', flag: 'https://flagcdn.com/w40/kh.png', dialCode: '+855' },
  { code: 'KI', name: 'Kiribati', flag: 'https://flagcdn.com/w40/ki.png', dialCode: '+686' },
  { code: 'KM', name: 'Comoros', flag: 'https://flagcdn.com/w40/km.png', dialCode: '+269' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: 'https://flagcdn.com/w40/kn.png', dialCode: '+1869' },
  { code: 'KP', name: 'North Korea', flag: 'https://flagcdn.com/w40/kp.png', dialCode: '+850' },
  { code: 'KR', name: 'South Korea', flag: 'https://flagcdn.com/w40/kr.png', dialCode: '+82' },
  { code: 'KW', name: 'Kuwait', flag: 'https://flagcdn.com/w40/kw.png', dialCode: '+965' },
  { code: 'KY', name: 'Cayman Islands', flag: 'https://flagcdn.com/w40/ky.png', dialCode: '+1345' },
  { code: 'KZ', name: 'Kazakhstan', flag: 'https://flagcdn.com/w40/kz.png', dialCode: '+7' },
  { code: 'LA', name: 'Laos', flag: 'https://flagcdn.com/w40/la.png', dialCode: '+856' },
  { code: 'LB', name: 'Lebanon', flag: 'https://flagcdn.com/w40/lb.png', dialCode: '+961' },
  { code: 'LC', name: 'Saint Lucia', flag: 'https://flagcdn.com/w40/lc.png', dialCode: '+1758' },
  { code: 'LI', name: 'Liechtenstein', flag: 'https://flagcdn.com/w40/li.png', dialCode: '+423' },
  { code: 'LK', name: 'Sri Lanka', flag: 'https://flagcdn.com/w40/lk.png', dialCode: '+94' },
  { code: 'LR', name: 'Liberia', flag: 'https://flagcdn.com/w40/lr.png', dialCode: '+231' },
  { code: 'LS', name: 'Lesotho', flag: 'https://flagcdn.com/w40/ls.png', dialCode: '+266' },
  { code: 'LT', name: 'Lithuania', flag: 'https://flagcdn.com/w40/lt.png', dialCode: '+370' },
  { code: 'LU', name: 'Luxembourg', flag: 'https://flagcdn.com/w40/lu.png', dialCode: '+352' },
  { code: 'LV', name: 'Latvia', flag: 'https://flagcdn.com/w40/lv.png', dialCode: '+371' },
  { code: 'LY', name: 'Libya', flag: 'https://flagcdn.com/w40/ly.png', dialCode: '+218' },
  { code: 'MA', name: 'Morocco', flag: 'https://flagcdn.com/w40/ma.png', dialCode: '+212' },
  { code: 'MC', name: 'Monaco', flag: 'https://flagcdn.com/w40/mc.png', dialCode: '+377' },
  { code: 'MD', name: 'Moldova', flag: 'https://flagcdn.com/w40/md.png', dialCode: '+373' },
  { code: 'ME', name: 'Montenegro', flag: 'https://flagcdn.com/w40/me.png', dialCode: '+382' },
  { code: 'MF', name: 'Saint Martin (French part)', flag: 'https://flagcdn.com/w40/mf.png', dialCode: '+590' },
  { code: 'MG', name: 'Madagascar', flag: 'https://flagcdn.com/w40/mg.png', dialCode: '+261' },
  { code: 'MH', name: 'Marshall Islands', flag: 'https://flagcdn.com/w40/mh.png', dialCode: '+692' },
  { code: 'MK', name: 'North Macedonia', flag: 'https://flagcdn.com/w40/mk.png', dialCode: '+389' },
  { code: 'ML', name: 'Mali', flag: 'https://flagcdn.com/w40/ml.png', dialCode: '+223' },
  { code: 'MM', name: 'Myanmar', flag: 'https://flagcdn.com/w40/mm.png', dialCode: '+95' },
  { code: 'MN', name: 'Mongolia', flag: 'https://flagcdn.com/w40/mn.png', dialCode: '+976' },
  { code: 'MO', name: 'Macao', flag: 'https://flagcdn.com/w40/mo.png', dialCode: '+853' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: 'https://flagcdn.com/w40/mp.png', dialCode: '+1670' },
  { code: 'MQ', name: 'Martinique', flag: 'https://flagcdn.com/w40/mq.png', dialCode: '+596' },
  { code: 'MR', name: 'Mauritania', flag: 'https://flagcdn.com/w40/mr.png', dialCode: '+222' },
  { code: 'MS', name: 'Montserrat', flag: 'https://flagcdn.com/w40/ms.png', dialCode: '+1664' },
  { code: 'MT', name: 'Malta', flag: 'https://flagcdn.com/w40/mt.png', dialCode: '+356' },
  { code: 'MU', name: 'Mauritius', flag: 'https://flagcdn.com/w40/mu.png', dialCode: '+230' },
  { code: 'MV', name: 'Maldives', flag: 'https://flagcdn.com/w40/mv.png', dialCode: '+960' },
  { code: 'MW', name: 'Malawi', flag: 'https://flagcdn.com/w40/mw.png', dialCode: '+265' },
  { code: 'MX', name: 'Mexico', flag: 'https://flagcdn.com/w40/mx.png', dialCode: '+52' },
  { code: 'MY', name: 'Malaysia', flag: 'https://flagcdn.com/w40/my.png', dialCode: '+60' },
  { code: 'MZ', name: 'Mozambique', flag: 'https://flagcdn.com/w40/mz.png', dialCode: '+258' },
  { code: 'NA', name: 'Namibia', flag: 'https://flagcdn.com/w40/na.png', dialCode: '+264' },
  { code: 'NC', name: 'New Caledonia', flag: 'https://flagcdn.com/w40/nc.png', dialCode: '+687' },
  { code: 'NE', name: 'Niger', flag: 'https://flagcdn.com/w40/ne.png', dialCode: '+227' },
  { code: 'NF', name: 'Norfolk Island', flag: 'https://flagcdn.com/w40/nf.png', dialCode: '+672' },
  { code: 'NG', name: 'Nigeria', flag: 'https://flagcdn.com/w40/ng.png', dialCode: '+234' },
  { code: 'NI', name: 'Nicaragua', flag: 'https://flagcdn.com/w40/ni.png', dialCode: '+505' },
  { code: 'NL', name: 'Netherlands', flag: 'https://flagcdn.com/w40/nl.png', dialCode: '+31' },
  { code: 'NO', name: 'Norway', flag: 'https://flagcdn.com/w40/no.png', dialCode: '+47' },
  { code: 'NP', name: 'Nepal', flag: 'https://flagcdn.com/w40/np.png', dialCode: '+977' },
  { code: 'NR', name: 'Nauru', flag: 'https://flagcdn.com/w40/nr.png', dialCode: '+674' },
  { code: 'NU', name: 'Niue', flag: 'https://flagcdn.com/w40/nu.png', dialCode: '+683' },
  { code: 'NZ', name: 'New Zealand', flag: 'https://flagcdn.com/w40/nz.png', dialCode: '+64' },
  { code: 'OM', name: 'Oman', flag: 'https://flagcdn.com/w40/om.png', dialCode: '+968' },
  { code: 'PA', name: 'Panama', flag: 'https://flagcdn.com/w40/pa.png', dialCode: '+507' },
  { code: 'PE', name: 'Peru', flag: 'https://flagcdn.com/w40/pe.png', dialCode: '+51' },
  { code: 'PF', name: 'French Polynesia', flag: 'https://flagcdn.com/w40/pf.png', dialCode: '+689' },
  { code: 'PG', name: 'Papua New Guinea', flag: 'https://flagcdn.com/w40/pg.png', dialCode: '+675' },
  { code: 'PH', name: 'Philippines', flag: 'https://flagcdn.com/w40/ph.png', dialCode: '+63' },
  { code: 'PK', name: 'Pakistan', flag: 'https://flagcdn.com/w40/pk.png', dialCode: '+92' },
  { code: 'PL', name: 'Poland', flag: 'https://flagcdn.com/w40/pl.png', dialCode: '+48' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: 'https://flagcdn.com/w40/pm.png', dialCode: '+508' },
  { code: 'PN', name: 'Pitcairn', flag: 'https://flagcdn.com/w40/pn.png', dialCode: '+64' },
  { code: 'PR', name: 'Puerto Rico', flag: 'https://flagcdn.com/w40/pr.png', dialCode: '+1' },
  { code: 'PS', name: 'Palestine', flag: 'https://flagcdn.com/w40/ps.png', dialCode: '+970' },
  { code: 'PT', name: 'Portugal', flag: 'https://flagcdn.com/w40/pt.png', dialCode: '+351' },
  { code: 'PW', name: 'Palau', flag: 'https://flagcdn.com/w40/pw.png', dialCode: '+680' },
  { code: 'PY', name: 'Paraguay', flag: 'https://flagcdn.com/w40/py.png', dialCode: '+595' },
  { code: 'QA', name: 'Qatar', flag: 'https://flagcdn.com/w40/qa.png', dialCode: '+974' },
  { code: 'RE', name: 'Réunion', flag: 'https://flagcdn.com/w40/re.png', dialCode: '+262' },
  { code: 'RO', name: 'Romania', flag: 'https://flagcdn.com/w40/ro.png', dialCode: '+40' },
  { code: 'RS', name: 'Serbia', flag: 'https://flagcdn.com/w40/rs.png', dialCode: '+381' },
  { code: 'RU', name: 'Russia', flag: 'https://flagcdn.com/w40/ru.png', dialCode: '+7' },
  { code: 'RW', name: 'Rwanda', flag: 'https://flagcdn.com/w40/rw.png', dialCode: '+250' },
  { code: 'SA', name: 'Saudi Arabia', flag: 'https://flagcdn.com/w40/sa.png', dialCode: '+966' },
  { code: 'SB', name: 'Solomon Islands', flag: 'https://flagcdn.com/w40/sb.png', dialCode: '+677' },
  { code: 'SC', name: 'Seychelles', flag: 'https://flagcdn.com/w40/sc.png', dialCode: '+248' },
  { code: 'SD', name: 'Sudan', flag: 'https://flagcdn.com/w40/sd.png', dialCode: '+249' },
  { code: 'SE', name: 'Sweden', flag: 'https://flagcdn.com/w40/se.png', dialCode: '+46' },
  { code: 'SG', name: 'Singapore', flag: 'https://flagcdn.com/w40/sg.png', dialCode: '+65' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', flag: 'https://flagcdn.com/w40/sh.png', dialCode: '+290' },
  { code: 'SI', name: 'Slovenia', flag: 'https://flagcdn.com/w40/si.png', dialCode: '+386' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: 'https://flagcdn.com/w40/sj.png', dialCode: '+47' },
  { code: 'SK', name: 'Slovakia', flag: 'https://flagcdn.com/w40/sk.png', dialCode: '+421' },
  { code: 'SL', name: 'Sierra Leone', flag: 'https://flagcdn.com/w40/sl.png', dialCode: '+232' },
  { code: 'SM', name: 'San Marino', flag: 'https://flagcdn.com/w40/sm.png', dialCode: '+378' },
  { code: 'SN', name: 'Senegal', flag: 'https://flagcdn.com/w40/sn.png', dialCode: '+221' },
  { code: 'SO', name: 'Somalia', flag: 'https://flagcdn.com/w40/so.png', dialCode: '+252' },
  { code: 'SR', name: 'Suriname', flag: 'https://flagcdn.com/w40/sr.png', dialCode: '+597' },
  { code: 'SS', name: 'South Sudan', flag: 'https://flagcdn.com/w40/ss.png', dialCode: '+211' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: 'https://flagcdn.com/w40/st.png', dialCode: '+239' },
  { code: 'SV', name: 'El Salvador', flag: 'https://flagcdn.com/w40/sv.png', dialCode: '+503' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', flag: 'https://flagcdn.com/w40/sx.png', dialCode: '+1721' },
  { code: 'SY', name: 'Syrian Arab Republic', flag: 'https://flagcdn.com/w40/sy.png', dialCode: '+963' },
  { code: 'SZ', name: 'Eswatini', flag: 'https://flagcdn.com/w40/sz.png', dialCode: '+268' },
  { code: 'TC', name: 'Turks and Caicos Islands', flag: 'https://flagcdn.com/w40/tc.png', dialCode: '+1649' },
  { code: 'TD', name: 'Chad', flag: 'https://flagcdn.com/w40/td.png', dialCode: '+235' },
  { code: 'TF', name: 'French Southern Territories', flag: 'https://flagcdn.com/w40/tf.png', dialCode: '+262' },
  { code: 'TG', name: 'Togo', flag: 'https://flagcdn.com/w40/tg.png', dialCode: '+228' },
  { code: 'TH', name: 'Thailand', flag: 'https://flagcdn.com/w40/th.png', dialCode: '+66' },
  { code: 'TJ', name: 'Tajikistan', flag: 'https://flagcdn.com/w40/tj.png', dialCode: '+992' },
  { code: 'TK', name: 'Tokelau', flag: 'https://flagcdn.com/w40/tk.png', dialCode: '+690' },
  { code: 'TL', name: 'Timor-Leste', flag: 'https://flagcdn.com/w40/tl.png', dialCode: '+670' },
  { code: 'TM', name: 'Turkmenistan', flag: 'https://flagcdn.com/w40/tm.png', dialCode: '+993' },
  { code: 'TN', name: 'Tunisia', flag: 'https://flagcdn.com/w40/tn.png', dialCode: '+216' },
  { code: 'TO', name: 'Tonga', flag: 'https://flagcdn.com/w40/to.png', dialCode: '+676' },
  { code: 'TR', name: 'Turkey', flag: 'https://flagcdn.com/w40/tr.png', dialCode: '+90' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: 'https://flagcdn.com/w40/tt.png', dialCode: '+1868' },
  { code: 'TV', name: 'Tuvalu', flag: 'https://flagcdn.com/w40/tv.png', dialCode: '+688' },
  { code: 'TW', name: 'Taiwan', flag: 'https://flagcdn.com/w40/tw.png', dialCode: '+886' },
  { code: 'TZ', name: 'Tanzania', flag: 'https://flagcdn.com/w40/tz.png', dialCode: '+255' },
  { code: 'UA', name: 'Ukraine', flag: 'https://flagcdn.com/w40/ua.png', dialCode: '+380' },
  { code: 'UG', name: 'Uganda', flag: 'https://flagcdn.com/w40/ug.png', dialCode: '+256' },
  { code: 'UM', name: 'U.S. Minor Outlying Islands', flag: 'https://flagcdn.com/w40/um.png', dialCode: '+1' },
  { code: 'US', name: 'United States', flag: 'https://flagcdn.com/w40/us.png', dialCode: '+1' },
  { code: 'UY', name: 'Uruguay', flag: 'https://flagcdn.com/w40/uy.png', dialCode: '+598' },
  { code: 'UZ', name: 'Uzbekistan', flag: 'https://flagcdn.com/w40/uz.png', dialCode: '+998' },
  { code: 'VA', name: 'Vatican City', flag: 'https://flagcdn.com/w40/va.png', dialCode: '+39' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: 'https://flagcdn.com/w40/vc.png', dialCode: '+1784' },
  { code: 'VE', name: 'Venezuela', flag: 'https://flagcdn.com/w40/ve.png', dialCode: '+58' },
  { code: 'VG', name: 'British Virgin Islands', flag: 'https://flagcdn.com/w40/vg.png', dialCode: '+1284' },
  { code: 'VI', name: 'U.S. Virgin Islands', flag: 'https://flagcdn.com/w40/vi.png', dialCode: '+1340' },
  { code: 'VN', name: 'Vietnam', flag: 'https://flagcdn.com/w40/vn.png', dialCode: '+84' },
  { code: 'VU', name: 'Vanuatu', flag: 'https://flagcdn.com/w40/vu.png', dialCode: '+678' },
  { code: 'WF', name: 'Wallis and Futuna', flag: 'https://flagcdn.com/w40/wf.png', dialCode: '+681' },
  { code: 'WS', name: 'Samoa', flag: 'https://flagcdn.com/w40/ws.png', dialCode: '+685' },
  { code: 'YE', name: 'Yemen', flag: 'https://flagcdn.com/w40/ye.png', dialCode: '+967' },
  { code: 'YT', name: 'Mayotte', flag: 'https://flagcdn.com/w40/yt.png', dialCode: '+262' },
  { code: 'ZA', name: 'South Africa', flag: 'https://flagcdn.com/w40/za.png', dialCode: '+27' },
  { code: 'ZM', name: 'Zambia', flag: 'https://flagcdn.com/w40/zm.png', dialCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', flag: 'https://flagcdn.com/w40/zw.png', dialCode: '+263' }
] as const;

export type Country = typeof countries[number];